### ISSUE TITLE
Providing a dockerfile

### ISSUE THREAD

**Issue by nimag42** [metno/TITAN#15]
Hi, 

Would you consider providing a Dockerfile and pushing it on Dockerhub like other metno's projects are ?

It will be simpler for me to deploy my app using your tool :)

Of course if it's not possible, I would understand.

Thank you.

**Comment by cristianlussana** [comment]
Hi,
Sorry for the delay in answering. We have no plan to provide a Dockerfile for this project at the moment.
Best,
Cristian

**Comment by fox91** [comment]
Hi @cristianlussana,
if you are interested I can create the dockerfile with all the necessary dependencies.
Let me know

**Comment by cristianlussana** [comment]
Hi @fox91 ,
at the moment we are not interested in having a dockerfile. We are currently working on the TITAN project to further develop it and this will also change a bit the way the github repository is organized.

**Comment by fox91** [comment]
No problem, I will look forward to new developments.
