### ISSUE TITLE
argparser doesn't work anymore

### ISSUE THREAD

**Issue by fox91** [metno/TITAN#18]
After the latest (version `0.6`) update of `argparser` dependency TITAN doesn't work anymore and print these error:

```
Error in (function (object, class, nargs)  : 
  Invalid argument value: expecting numeric but got: (NA).
Calls: parse_args -> mapply -> <Anonymous>
Execution halted
```

Instead if you force the old version `0.4` it works correctly.

Someone can check if is a TITAN issue or a `argparser` issue and how to solve?

**Comment by cristianlussana** [comment]
Yes, I've noticed the same error with other R-programs I'm using. I'll check that. Thanks.

**Comment by cristianlussana** [comment]
given the discussion here:
https://bitbucket.org/djhshih/argparser/issues/18/negative-numbers-cannot-be-passed-as
I believe this is due to a bug in argparser that is probably being fixed. I suggest we wait for argparser ver 0.7 (should be submitted by the end of January)

**Comment by fox91** [comment]
Have you got to try this new version to make sure that the problems have actually been solved?

**Comment by cristianlussana** [comment]
Hi! Meglio tardi che mai... sorry for the delay in answering. I tried argparser version 0.7.1 but it looks like it is not plug-and-play with argparser. Stick to version 0.4, which works.
