### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by fox91** [metno/TITAN#19]
I saw that `metno` recently released these other projects: [offline-surfex-forcing](https://github.com/metno/offline-surfex-forcing) and [titanlib](https://github.com/metno/titanlib).

It seems that the former uses TITAN but not the one in R of this project, while the latter is a rewrite of this?

I wanted to know if this project will be continued or will be replaced by `titanlib` because we have encountered bugs and we have to decide whether to fix them here or move on to other libraries in case this is deprecated.

Thanks

**Comment by tnipen** [comment]
Sorry for the confusion, we are in the process of reorganising these repositories. Basically, we recognize the need to be able to use the algorithms in TITAN in other non-command-line workflows.

We have therefore started to developing a C++ library called titanlib, which contains the algorithms from TITAN. QC functions from this library can be called from for example python or R.

The TITAN repository will still exist and will be the same command-line tool as before, but instead it will make calls to titanlib. If you do have bugs, please let us know as we would like to improve both the command-line tool and the library.

**Comment by meierflo** [comment]
Can the DEM check also be called from python in titanlib or is it not yet implemented?

**Comment by cristianlussana** [comment]
Please refer to the titanlib wiki here https://github.com/metno/titanlib/wiki
